DROP TABLE WARDROBE_INFO_TMP1;
DROP TABLE WARDROBE_INFO_TMP2;
DROP TABLE WEATHER_INFO_TMP1;
DROP TABLE WEATHER_INFO_TMP2;
DROP TABLE WEATHER_INFO_TMP3;
DROP TABLE USER_INFO_TMP1;
DROP TABLE USER_INFO_TMP2;