EXPORT "WARDROBE_AP"."WARDROBE_INFO_TMP1" AS CSV INTO '/backup_nfs/work/20200828_export' WITH REPLACE;
EXPORT "WARDROBE_AP"."WARDROBE_INFO_TMP2" AS CSV INTO '/backup_nfs/work/20200828_export' WITH REPLACE;
EXPORT "WARDROBE_AP"."WEATHER_INFO_TMP1" AS CSV INTO '/backup_nfs/work/20200828_export' WITH REPLACE;
EXPORT "WARDROBE_AP"."WEATHER_INFO_TMP2" AS CSV INTO '/backup_nfs/work/20200828_export' WITH REPLACE;
EXPORT "WARDROBE_AP"."WEATHER_INFO_TMP3" AS CSV INTO '/backup_nfs/work/20200828_export' WITH REPLACE;
EXPORT "WARDROBE_AP"."USER_INFO_TMP1" AS CSV INTO '/backup_nfs/work/20200828_export' WITH REPLACE;
EXPORT "WARDROBE_AP"."USER_INFO_TMP2" AS CSV INTO '/backup_nfs/work/20200828_export' WITH REPLACE;