INSERT INTO "PIOAP"."WARDROBE_INFO_TMP1" SELECT * FROM WARDROBE_INFO WHERE CATEGORY_CD = '1';
INSERT INTO "PIOAP"."WARDROBE_INFO_TMP2" SELECT * FROM WARDROBE_INFO WHERE CATEGORY_CD != '1' or CATEOGRY IS NULL;;
INSERT INTO "PIOAP"."WEATHER_INFO_TMP1" SELECT * FROM WEATHER_INFO ;
INSERT INTO "PIOAP"."WEATHER_INFO_TMP2" SELECT * FROM WEATHER_INFO ;
INSERT INTO "PIOAP"."WEATHER_INFO_TMP3" SELECT * FROM WEATHER_INFO ;
INSERT INTO "PIOAP"."USER_INFO_TMP1" SELECT * FROM USER_INFO WHERE BIRTH_DATE < '2000/09/30';
INSERT INTO "PIOAP"."USER_INFO_TMP2" SELECT * FROM USER_INFO WHERE BIRTH_DATE >= '2000/09/30';