SELECT COUNT(*) FROM WARDROBE_INFO;

SELECT COUNT(*) FROM WEATHER_INFO;


SELECT COUNT(*) FROM USER_INFO;

SELECT COUNT(*) FROM CONSULT_PARTY_INFO;
SELECT COUNT(*) FROM CC_Q_INFO;
SELECT COUNT(*) FROM CC_A_INFO;