SELECT COUNT(*) FROM WARDROBE_INFO_TMP1;
SELECT COUNT(*) FROM WARDROBE_INFO_TMP2;
SELECT COUNT(*) FROM WEATHER_INFO_TMP1;
SELECT COUNT(*) FROM WEATHER_INFO_TMP2;
SELECT COUNT(*) FROM WEATHER_INFO_TMP3;
SELECT COUNT(*) FROM USER_INFO_TMP1;
SELECT COUNT(*) FROM USER_INFO_TMP2;