SELECT COUNT(*) FROM WARDROBE_INFO WHERE CATEGORY_CD = '1';
SELECT COUNT(*) FROM WARDROBE_INFO WHERE CATEGORY_CD != '1' or CATEOGRY IS NULL;;
SELECT COUNT(*) FROM WEATHER_INFO ;
SELECT COUNT(*) FROM WEATHER_INFO ;
SELECT COUNT(*) FROM WEATHER_INFO ;
SELECT COUNT(*) FROM USER_INFO WHERE BIRTH_DATE < '2000/09/30';
SELECT COUNT(*) FROM USER_INFO WHERE BIRTH_DATE >= '2000/09/30';