TRUNCATE TABLE WARDROBE_INFO_TMP1;
TRUNCATE TABLE WARDROBE_INFO_TMP2;
TRUNCATE TABLE WEATHER_INFO_TMP1;
TRUNCATE TABLE WEATHER_INFO_TMP2;
TRUNCATE TABLE WEATHER_INFO_TMP3;
TRUNCATE TABLE USER_INFO_TMP1;
TRUNCATE TABLE USER_INFO_TMP2;